# Generated by Django 5.2.6 on 2025-09-26 13:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=20)),
                ('program', models.CharField(choices=[('IoT Development', 'IoT Development'), ('Software Development', 'Software Development'), ('Data Science', 'Data Science')], max_length=50)),
                ('year', models.CharField(default='2023', max_length=10)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive'), ('On Leave', 'On Leave'), ('Pending', 'Pending')], default='Active', max_length=20)),
                ('avatar', models.URLField(blank=True, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('emergencyContact', models.CharField(blank=True, max_length=100, null=True)),
                ('gpa', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(4)])),
                ('enrollmentDate', models.DateField()),
                ('courses', models.JSONField(blank=True, default=list)),
                ('dateOfBirth', models.DateField(blank=True, null=True)),
                ('credits', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('expectedGraduation', models.DateField(blank=True, null=True)),
                ('idNumber', models.CharField(max_length=50, unique=True)),
                ('studentType', models.CharField(blank=True, choices=[('Internee', 'Internee'), ('Trainee', 'Trainee')], max_length=20, null=True)),
                ('interneeType', models.CharField(blank=True, choices=[('University', 'University'), ('High School', 'High School')], max_length=20, null=True)),
                ('studyStatus', models.CharField(blank=True, choices=[('Still Studying', 'Still Studying'), ('Graduated', 'Graduated')], max_length=20, null=True)),
                ('paymentStatus', models.CharField(blank=True, choices=[('Paid', 'Paid'), ('Pending', 'Pending'), ('Partial', 'Partial')], max_length=20, null=True)),
                ('totalFees', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('paidAmount', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('remainingAmount', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('enrollmentType', models.CharField(blank=True, choices=[('Full-time', 'Full-time'), ('Part-time', 'Part-time')], max_length=20, null=True)),
                ('startDate', models.DateField(blank=True, null=True)),
                ('endDate', models.DateField(blank=True, null=True)),
                ('attendance', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('performance', models.CharField(blank=True, choices=[('Excellent', 'Excellent'), ('Good', 'Good'), ('Average', 'Average'), ('Poor', 'Poor')], max_length=20, null=True)),
                ('achievements', models.JSONField(blank=True, default=list)),
                ('projects', models.JSONField(blank=True, default=list)),
                ('extracurricular', models.JSONField(blank=True, default=list)),
                ('totalPoints', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('totalProjects', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('certifications', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('overallAttendance', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('presentDays', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('absentDays', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('lateDays', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('excusedAbsences', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('currentStreak', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('lastAttendance', models.DateField(blank=True, null=True)),
                ('monthlyData', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
