# Generated by Django 5.2.6 on 2025-09-26 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='feedback',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
