# Generated by Django 5.2.6 on 2025-09-26 14:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_student_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='academic_standing',
            field=models.CharField(blank=True, choices=[('Good Standing', 'Good Standing'), ('Academic Warning', 'Academic Warning'), ('Academic Probation', 'Academic Probation')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='assignments',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='student',
            name='completed_credits',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='student',
            name='cumulative_gpa',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(4)]),
        ),
        migrations.AddField(
            model_name='student',
            name='current_semester',
            field=models.CharField(default='Spring 2024', max_length=20),
        ),
        migrations.AddField(
            model_name='student',
            name='grades',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
