# Generated by Django 5.2.7 on 2025-11-16 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0008_student_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='program',
            field=models.CharField(choices=[('IoT Development', 'IoT Development'), ('Software Development', 'Software Development')], max_length=50),
        ),
    ]
