# Generated by Django 5.2.6 on 2025-10-28 09:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TrashBin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_type', models.CharField(choices=[('student', 'Student'), ('employee', 'Employee'), ('activity', 'Activity'), ('other', 'Other')], max_length=20)),
                ('item_id', models.CharField(max_length=100)),
                ('item_data', models.JSONField()),
                ('deleted_at', models.DateTimeField(auto_now_add=True)),
                ('can_restore', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trash_items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-deleted_at'],
            },
        ),
    ]
