# Generated by Django 5.2.7 on 2025-11-15 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='reference',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='status',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='type',
        ),
        migrations.AddField(
            model_name='transaction',
            name='screenshot',
            field=models.ImageField(blank=True, null=True, upload_to='transaction_screenshots/'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='category',
            field=models.CharField(choices=[('Salary', 'Salary'), ('Rent', 'Rent'), ('Utilities', 'Utilities'), ('Groceries', 'Groceries'), ('Transportation', 'Transportation'), ('Entertainment', 'Entertainment'), ('Healthcare', 'Healthcare'), ('Education', 'Education'), ('Other', 'Other')], max_length=100),
        ),
    ]
