# Generated by Django 5.2.7 on 2025-11-15 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_remove_transaction_reference_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='type',
            field=models.CharField(blank=True, choices=[('Income', 'Income'), ('Expense', 'Expense')], max_length=10, null=True),
        ),
    ]
