# Generated by Django 5.2.7 on 2025-11-11 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0003_employee_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(choices=[('academic', 'Academic Department'), ('catering', 'Catering Department'), ('finance', 'Finance Department'), ('discipline_welfare', 'Discipline & Welfare Department')], max_length=50, unique=True),
        ),
    ]
