# Generated by Django 5.2.7 on 2025-11-11 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0004_alter_department_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='idNumber',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
